default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: debug-statements
      - id: detect-private-key
      - id: check-yaml
      - id: check-toml
      - id: check-executables-have-shebangs

        exclude: _pytest/(debugging|hookspec).py
        language_version: python3

  - repo: https://github.com/rtts/djhtml
    rev: "3.0.6"
    hooks:
      - id: djhtml
      - id: djcss

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.15.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.2"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
