# Generated by Django 4.2.7 on 2023-11-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_place", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storagebox",
            options={"verbose_name_plural": "StorageBoxes"},
        ),
        migrations.AddField(
            model_name="storagebox",
            name="monthly_price",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Monthly price (€)"
            ),
        ),
    ]
